title:
  en: Services
  fr: Services

services:

  - en: Content Development
    fr: Développement de contenu

  - en: Event Curation
    fr: Commissariat d’événements

  - en: Editorial Strategy
    fr: Stratégie éditoriale

  - en: Directing
    fr: Réalisation

  - en: Production
    fr: Production

  - en: Creative Direction
    fr: Direction de création

  - en: Performance
    fr: Performances artistiques

  - en: Brand Collaborations
    fr: Collaborations de marque
